name: Release notes to Discord
author: Aik-10
description: Custom Discord release notes.

inputs:
  webhook_url:
    description: Discord's webhook url.
    required: true
  color:
    description: Embed message color.
    required: false
    default: "2105893"
  username:
    description: String username.
    required: false
  avatar_url:
    description: Discord profile URL.
    required: false
  footer_timestamp:
    description: Timestamp for the footer.
    required: false
  override_url:
    description: Hiding github repository address.
    required: false
  replace_change:
    description: String to replace what chagnes.
    required: false
  replace_contributors:
    description: String to replace new contributors.
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
  post: 'dist/index.js'

branding:
  icon: anchor
  color: blue
